services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./Uploads:/app/Uploads
      - ./entries.json:/app/entries.json
      - ./pages.json:/app/pages.json
      - ./cred.json:/app/cred.json
    restart: unless-stopped
